#!/usr/bin/env sh
# wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
curl -fLo ~/.config/nvim/init.vim --create-dirs https://raw.githubusercontent.com/ApplicationDeveloper/dotfiles/master/.config/nvim/init.vim
curl -fLo ~/.tmux.conf https://raw.githubusercontent.com/ApplicationDeveloper/dotfiles/master/.tmux.conf
curl -fLo ~/.gitignore https://raw.githubusercontent.com/ApplicationDeveloper/dotfiles/master/.gitignore

sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
               https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

curl -sL https://deb.nodesource.com/setup_15.x | bash -
sudo apt install nodejs

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update
sudo apt install yarn

nvim +PlugInstall +qall
